// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.windows:
        return web;
      default:
        return android;
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyWZOEDlWyGGHftlRqzsNjFIKD9sXR_u0',
    appId: '1:1069640136187:android:f3be5c885566b7ff9ac75e',
    messagingSenderId: '1069640136187',
    projectId: 'dd-online-web',
    storageBucket: 'dd-online-web.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyWZOEDlWyGGHftlRqzsNjFIKD9sXR_u0',
    appId: '1:1069640136187:ios:f3be5c885566b7ff9ac75e',
    messagingSenderId: '1069640136187',
    projectId: 'dd-online-web',
    storageBucket: 'dd-online-web.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyWZOEDlWyGGHftlRqzsNjFIKD9sXR_u0',
    appId: '1:1069640136187:web:f3be5c885566b7ff9ac75e',
    messagingSenderId: '1069640136187',
    projectId: 'dd-online-web',
    authDomain: 'dd-online-web.firebaseapp.com',
    storageBucket: 'dd-online-web.firebasestorage.app',
    measurementId: 'G-4SQYH9LBKQ',
  );
}