import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;
  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  static const _ky = {
    'settings': 'Жөндөөлөр',
    'language': 'Тил',
    'notifications': 'Билдирмелер',
    'dark_mode': 'Күңүрт режим',
    'profile': 'Профил',
    'cache': 'Кэшти тазалоо',
    'support': 'Колдоо',
    'terms': 'Эрежелер',
    'home': 'Башкы',
    'cart': 'Себет',
    'favorites': 'Тандамалар',
    'chat': 'Чат',
    'shop': 'Дүкөн',
    'search': 'Издөө',
    'search_hint': 'Товар издеңиз...',
    'save': 'Сактоо',
    'cancel': 'Жокко чыгаруу',
    'delete': 'Өчүрүү',
    'yes': 'Ооба',
    'no': 'Жок',
    'loading': 'Жүктөлүүдө...',
    'error': 'Ката кетти',
    'success': 'Ийгиликтүү',
    'ok': 'Жарайт',
    'back': 'Артка',
    'close': 'Жабуу',
    'sign_out': 'Чыгуу',
    'product': 'Товар',
    'price': 'Баасы',
    'add_to_cart': 'Себетке кошуу',
    'in_cart': 'Себетте бар',
    'buy_now': 'Азыр сатып алуу',
    'description': 'Сүрөттөмө',
    'sizes': 'Размерлер',
    'colors': 'Түстөр',
    'characteristics': 'Характеристикалар',
    'similar': 'Окшош товарлар',
    'no_products': 'Табылган жок',
    'search_empty': 'Башка сөз менен издеп көрүңүз',
    'popular': '🔥 Таанымал',
    'newest': '🆕 Жаңы товарлар',
    'refresh': 'Жаңылоо',
    'filter': 'Чыпкалоо',
    'filter_reset': 'Тазалоо',
    'nearby': 'Мага жакын',
    'nearby_error':
        'Жайгашкан жериңизди аныктоо мүмкүн болбоду. Геолокацияга уруксат бериңиз.',
    'nearby_count': 'жакын товар',
    'hours_start': 'Башталат',
    'hours_end': 'Аяктайт',
    'hours_workdays': 'Жумуш күндөрү',
    'hours_mon_fri': 'Дш-Жм',
    'hours_mon_sat': 'Дш-Шб',
    'hours_mon_sun': 'Дш-Жк',
    'hours_no_sun': 'Жк күн эмес',
    'hours_daily': 'Күн сайын',
    'hours_saved': '✅ Иштөө убактысы сакталды',
    'results': 'натыйжа',
    'camera_search': 'Издөө камерасы',
    'camera_soon': 'Жакында кошулат! 🚀\nТовардын сүрөтүн тартып издей аласыз.',
    'seller': 'Сатуучу',
    'container': 'Жайгашкан жери',
    'work_hours': 'Иш убактысы',
    'route': 'Маршрут түзүү',
    'write_seller': 'Сатуучуга жазуу',
    'select_size': 'Размер тандаңыз',
    'add_review': 'Пикир жазуу',
    'reviews': 'Пикирлер',
    'no_reviews': 'Азырынча пикир жок',
    'share': 'Бөлүшүү',
    'cart_empty': 'Себет бош',
    'cart_empty_desc': 'Товарларды себетке кошуңуз',
    'total': 'Жалпы',
    'checkout': 'Заказ берүү',
    'quantity': 'Саны',
    'favorites_empty': 'Тандамалар бош',
    'favorites_empty_desc': 'Жаккан товарларды ♥ басып кошуңуз',
    'welcome_title': 'Дордойдун онлайн базары',
    'sign_in_google': 'Google менен кирүү',
    'sign_in_terms': 'Кирүү менен Колдонуу шарттарына\nкелишесиз',
    'cache_cleared': 'Кэш тазаланды ✅',
    'cache_error': 'Ката',
    'no_chats': 'Чаттар жок',
    'type_message': 'Билдирүү жазыңыз...',
    'send': 'Жиберүү',
    'seller_title': 'Сатуучу',
    'login': 'Кирүү',
    'register': 'Катталуу',
    'shop_title': 'Дүкөнүңүздү башкарыңыз!',
    'shop_desc':
        'DD Online аркылуу товарларыңызды\nДордой базарынан дүйнөгө сатыңыз',
    'add_product': 'Товар кошуу',
    'my_products': 'Менин товарларым',
    'no_size': 'Размерсиз',
    'open': 'Ачык',
    'closed': 'Жабык',
    'no_info': 'Маалымат жок',
    'in_stock': 'Запаста бар',
    'out_of_stock': 'Запаста жок',
    'pcs': 'дана',
    'location_denied': '📍 Уруксат бериңиз',
    'location_unknown': 'Сатуучунун картадагы жери белгисиз',
    'seller_no_info': 'Сатуучу маалыматы жок!',
    'chat_login_required': 'Чат үчүн кирүү керек!',
    'own_product': 'Бул сиздин өз товарыңыз!',
    '2gis_not_installed': '2ГИС орнотулган жок',
    '2gis_download_hint': 'Маршрут үчүн 2ГИС тиркемесин жүктөп алыңыз.',
    'download': 'Жүктөп алуу',
    'nav_step1': 'Төмөндөгү баскычты басыңыз',
    'nav_step2': '2ГИС тиркемеси ачылат',
    'nav_step3': '"Маршрут түзүү" баскычын басып жолго чыгыңыз',
    'open_2gis': '2ГИС менен маршрут түзүү',
    'login_error': 'Кирүүдө ката кетти',
    'seller_login': 'Сатуучу катары кирүү',
    'email_not_found': 'Почта тиркемеси табылбады',
    'messages': 'Билдирүүлөр',
    'selected': 'тандалды',
    'delete_chat': 'Чатты өчүрүү',
    'delete_chat_confirm': 'чатты өчүрөсүзбү?',
    'select_all': 'Баарын тандоо',
    'deselect_all': 'Баарын алып салуу',
    'new_chat': 'Жаңы чат',
    'cart_clear_title': 'Себетти тазалоо',
    'cart_clear_confirm': 'Бардык товарларды өчүрөсүзбү?',
    'back_to_products': 'Товарларга кайт',
    'size_label': 'Размер',
    'items_count': 'Товарлар саны:',
    'total_price': 'Жалпы баасы:',
    'order_placed': 'Буйрутма берилди!',
    'order_placed_desc':
        'Сиздин буйрутмаңыз кабыл алынды! Сатуучу менен чат аркылуу байланышыңыз.',
    'great': 'Жакшы!',
    'prod_all': 'Баары',
    'prod_empty': 'Товарыңыз жок',
    'prod_empty_hint': 'Товар кошуу үчүн төмөнкү + баскычты басыңыз',
    'prod_empty_cat': 'Бул категорияда товар жок',
    'prod_empty_cat_hint': 'Башка категорияны тандаңыз',
    'prod_delete_title': 'Товарды өчүрүү',
    'prod_delete_confirm': 'товарын өчүрөсүзбү?',
    'prod_delete_yes': 'Ооба, өчүр',
    'prod_deleted': 'Товар өчүрүлдү',
    'prod_delete_error': 'Өчүрүүдө ката',
    'prod_load_error': 'Товарларды жүктөөдө ката',
    'prod_img_upload_fail': 'Сүрөт жүктөлбөдү',
    'prod_check_internet': 'Интернет байланышын текшериңиз',
    'discount_title': '🏷️ Арзандатуу белгилөө',
    'discount_original_price': 'Баштапкы баа',
    'discount_percent_label': 'Арзандатуу пайызы (0–100)',
    'discount_label': 'арзандатуу',
    'discount_saved': 'сомго арзандады',
    'discount_add_btn': 'Аксияга кошуу',
    'discount_remove_btn': 'Аксияны алып салуу',
    'discount_removed': 'Аксия алынып салынды',
    'discount_saved_msg': '✅ Аксия сакталды! Товар акциялар бөлүмүнө кошулду.',
    'prod_dialog_add': 'Товар кошуу',
    'prod_dialog_edit': 'Товар өзгөртүү',
    'prod_field_image': '🖼️ Товардын сүрөтү *',
    'prod_field_name': '📝 Товардын аты *',
    'prod_hint_name': 'Мисалы: Кара жибек көйнөк',
    'prod_field_price': '💰 Баасы (сом) *',
    'prod_hint_price': 'Мисалы: 1200',
    'prod_field_main_cat': '🗂️ Негизги категория *',
    'prod_field_sub_cat': '📁 Кичи категория',
    'prod_sub_cat_general': 'Жалпы',
    'prod_field_colors': '🎨 Түстөр (каалоо боюнча)',
    'prod_size_men': '👔 Эркектер кийим размери',
    'prod_size_women': '👗 Аялдар кийим размери',
    'prod_size_kids': '👶 Балдар жашы / размери',
    'prod_size_school': '📏 Мектеп формасы размери (бой боюнча)',
    'prod_size_shoes': '👟 Бут кийим размери (балдар 16-35, чоңдор 36-47)',
    'prod_size_fabric': '🧵 Метраж тандаңыз',
    'prod_size_default': '📏 Размерлер тандаңыз',
    'prod_field_brand': '🏷️ Бренд',
    'prod_hint_brand_tech': 'Мисалы: Samsung, Apple, LG',
    'prod_field_model': '📋 Модель',
    'prod_hint_model': 'Мисалы: Galaxy S24, iPhone 15',
    'prod_field_spec': '🔌 Техникалык мүнөздөмө',
    'prod_hint_spec': 'Мисалы: 256GB, 4K, 2000Вт',
    'prod_hint_brand_beauty': 'Мисалы: Nivea, L\'Oreal',
    'prod_field_volume': '🧴 Көлөмү / Салмагы',
    'prod_hint_volume': 'Мисалы: 200мл, 50г',
    'prod_hint_brand_auto': 'Мисалы: Bosch, Michelin',
    'prod_field_car_compat': '🚗 Кайсы машинага туура келет',
    'prod_hint_car_compat': 'Мисалы: Toyota Camry, Kia Cerato',
    'prod_field_stock': '📦 Складдагы саны',
    'prod_hint_stock': 'Мисалы: 50',
    'prod_field_desc': '📄 Сүрөттөмө',
    'prod_hint_desc': 'Товар жөнүндө кыскача маалымат...',
    'prod_required_note': '* белгиленген талаалар милдеттүү.',
    'prod_err_name': 'Товардын атын жазыңыз!',
    'prod_err_price': 'Туура баа жазыңыз!',
    'prod_err_image': 'Сүрөт тандаңыз!',
    'prod_uploading': 'Сүрөт жүктөлүп жатат...',
    'prod_uploaded': '✅ Сүрөт жүктөлдү',
    'prod_saving': 'Товар сакталып жатат...',
    'prod_added': '✅ Товар ийгиликтүү кошулду!',
    'prod_updated': '✅ Товар жаңыртылды!',
    'prod_save_error': 'Ката чыкты',
    'prod_btn_save': 'Товарды сактоо',
    'prod_btn_update': 'Өзгөртүүлөрдү сактоо',
    'prod_img_tap': 'Сүрөт кошуу үчүн басыңыз',
    'prod_img_camera': 'Камера менен тартуу',
    'prod_img_gallery': 'Галереядан тандоо',
    'prod_img_pick_error': 'Сүрөт тандоодо ката',
    'banner_product_label': '🛍 Товар',
    'banner_stock_label': 'Складда',
    'currency': 'с',
    'pending_title': 'Өтүнүчүңүз каралууда',
    'pending_desc':
        'Сиздин катталуу өтүнүчүңүз администратор\nтарабынан текшерилүүдө. Бекитилгенде\nдүкөнүңүздү башкара аласыз.',
    'pending_btn_home': 'Башкы баракка кайтуу',
    'rejected_title': 'Өтүнүч четке кагылды',
    'rejected_desc':
        'Кайра аракет кылуу үчүн администратор менен байланышыңыз.',
    'reg_title': 'Катталуу',
    'reg_heading': 'Дүкөнүңүздү ачыңыз!',
    'reg_subheading': 'Маалыматтарыңызды толтуруңуз',
    'reg_label_name': 'Аты-жөнү',
    'reg_hint_name': 'Мисалы: Айгерим Осмонова',
    'reg_label_age': 'Жашы',
    'reg_hint_age': 'Мисалы: 28',
    'reg_label_container': 'Контейнер номери же дүкөндүн аты',
    'reg_hint_container': 'Мисалы: 4-катар, А-12',
    'reg_label_shop': 'Дүкөндүн аты (милдеттүү эмес)',
    'reg_hint_shop': 'Мисалы: Айгерим Shop',
    'reg_label_phone': 'Телефон номери',
    'reg_label_pass': 'Пароль',
    'reg_hint_pass': 'Кеминде 8 символ, баш/кичи тамга, сан, белги',
    'reg_label_pass_confirm': 'Паролду кайталаңыз',
    'reg_btn_open': '🏪  Дүкөн ачуу',
    'reg_have_account': 'Аккаунтуңуз барбы? Кирүү',
    'reg_err_name': 'Аты-жөнүңүздү жазыңыз',
    'reg_err_age': 'Жашыңызды туура жазыңыз',
    'reg_err_container': 'Контейнер номерин же дүкөндүн атын жазыңыз',
    'reg_err_phone': 'Телефон номерин толук жазыңыз',
    'reg_err_pass_mismatch': 'Пароль дал келген жок',
    'terms_title': 'Эрежелер жана купуялык саясаты',
    'terms_s1_title': '1. Жалпы шарттар',
    'terms_s1_body':
        'DD Online — Дордой базарындагы сатуучулар менен сатып алуучуларды бириктирүүчү онлайн платформа. Колдонмону орнотуу жана колдонуу менен сиз ушул бетте көрсөтүлгөн эрежелерди жана купуялык саясатын кабыл алгандыгыңызды тастыктайсыз.',
    'terms_s2_title': '2. Платформанын ролу',
    'terms_s2_body':
        'DD Online товарларды өзү сатпайт. Платформа сатуучулар менен сатып алуучуларды байланыштыруу, товарларды издеп табуу жана дүкөнгө чейинки маршрутту көрсөтүү үчүн кызмат кылат. Товардын баасы, сапаты, бар-жоктугу жана сатуу шарттары үчүн жоопкерчиликти ал товарды жарыялаган сатуучу өзү тартат.',
    'terms_s3_title': '3. Колдонуучунун милдеттери',
    'terms_s3_body':
        'Колдонуучу каттоодо чыныгы маалымат көрсөтүүгө, башка колдонуучуларга жана сатуучуларга сылык мамиле кылууга мыйзамга жат, алдамчы же зыян келтирүүчү мазмун жайгаштырбоого милдеттенет. Бул эрежелер бузулган учурда профиль убактылуу же биротоло бөгөттөлүшү мүмкүн.',
    'terms_s4_title': '4. Сатуучулар үчүн эрежелер',
    'terms_s4_body':
        'Сатуучу жарыялаган товардын сүрөтү, баасы жана сүрөттөмөсү чындыкка дал келиши керек. Тыюу салынган, контрафакттык же мыйзамсыз товарларды жарыялоого жол берилбейт. Администрация шектүү же эрежеге каршы жарыяларды алдын ала эскертүүсүз өчүрүү же сатуучунун катталуусун токтотуу укугун сактайт.',
    'terms_s5_title': '5. Купуялык саясаты',
    'terms_s5_body':
        'Биз сиздин атыңыз, телефон номериңиз, жайгашкан жайыңыз (геолокация) жана колдонмо ичиндеги жазышуу тарыхы сыяктуу маалыматтарды чогултабыз. Бул маалымат төмөнкү максаттарда колдонулат: каттоо жана аутентификация, сатуучу менен сатып алуучуну байланыштыруу, дүкөнгө маршрут түзүү, колдонмонун иштөө сапатын жакшыртуу жана жарнама/билдирүүлөрдү жөнөтүү.',
    'terms_s6_title': '6. Маалыматты сактоо жана коргоо',
    'terms_s6_body':
        'Колдонуучунун маалыматы шифрленген серверлерде сакталат жана үчүнчү тараптарга сатылбайт. Маалымат сатуучу менен сатып алуучунун ортосундагы байланышты ишке ашыруу, статистика жана коопсуздук максатында гана колдонулушу мүмкүн. Колдонуучу каалаган убакта өз профилин жана жекелик маалыматтарын өчүрүүнү сурана алат.',
    'terms_s7_title': '7. Геолокация жана картадан колдонуу',
    'terms_s7_body':
        'Колдонмо "Маршрут түзүү" функциясын иштетүү үчүн сиздин жайгашкан жериңизге уруксат сурайт. Бул маалымат сиздин түзмөгүңүздө гана пайдаланылат жана 2ГИС сыяктуу үчүнчү тарап тиркемесине маршрут түзүү үчүн жөнөтүлөт.',
    'terms_s8_title': '8. Эрежелердин өзгөрүүсү',
    'terms_s8_body':
        'Администрация бул эрежелерди жана купуялык саясатын мезгил-мезгили менен жаңыртып турат. Маанилуу өзгөрүүлөр тууралуу колдонуучуларга колдонмо аркылуу кабарлоо жасалат.',
    'terms_s9_title': '9. Байланыш',
    'terms_s9_body':
        'Суроо-талаптар, даттануулар же сунуштар үчүн биз менен төмөнкү байланыш аркылуу кайрылууга болот:',
    'terms_contact_addr': 'Дордой базары, Бишкек, Кыргызстан',
    'terms_disclaimer':
        'Бул документ маалымат берүү максатында түзүлгөн жана юридикалык консультация эмес.',
    'cat_label': 'Категория',
    'cat_newest': 'Жаңы товарлар',
    'cat_popular': 'Таанымал',
    'cat_select': 'Категория тандоо',
    'filter_sort': 'Сорттоо',
    'sort_popular': 'Популярдуу',
    'sort_price_asc': 'Баасы: Арзандан',
    'sort_price_desc': 'Баасы: Кымбаттан',
    'sort_rating': 'Рейтинги жогору',
    'sort_newest': 'Жаңылары',
    'filter_apply': 'Колдонуу',
    'filter_count_suffix': 'фильтр',
    'map_title': 'Дүкөнчүлөрдүн тизмеги.',
    'map_store_count': 'дүкөн',
    'map_search_hint': 'Дүкөн же контейнер издөө...',
    'map_no_location': 'дүкөндүн локациясы кошулган жок',
    'map_not_found': 'Дүкөн табылган жок',
    'map_try_search': 'Издөөнү өзгөртүп көрүңүз',
    // Негизги категориялар
    'cat_1': 'Кийим-кече',
    'cat_2': 'Бут кийим',
    'cat_3': 'Аксессуарлар',
    'cat_4': 'Электроника',
    'cat_5': 'Үй буюмдар',
    'cat_6': 'Техника',
    'cat_7': 'Спорт',
    'cat_8': 'Балдар',
    'cat_9': 'Сулуулук',
    'cat_10': 'Гигиена',
    'cat_11': 'Азык-түлүк',
    'cat_12': 'Автотовар',
    'cat_13': 'Китеп/Канцтовар',
    'cat_14': 'Кездеме/Тигүү',
    'cat_15': 'Куралдар',
    'cat_16': 'Оюн/Эглентүү',
    'cat_17': 'Багчылык',
    'cat_18': 'Жаныбарлар',

    // Кичи категориялар — 1 (Кийим-кече)
    'cat_1_1': 'Баары',
    'cat_1_2': 'Эркектер',
    'cat_1_3': 'Аялдар',
    'cat_1_4': 'Балдар',
    'cat_1_5': 'Мектеп формасы',
    'cat_1_6': 'Кышкы кийим',
    'cat_1_7': 'Жайкы кийим',
    'cat_1_8': 'Спорт кийими',
    'cat_1_9': 'Жумушчу кийим',
    'cat_1_10': 'Улуттук кийим',

    // 2 (Бут кийим)
    'cat_2_1': 'Баары',
    'cat_2_2': 'Эркектер',
    'cat_2_3': 'Аялдар',
    'cat_2_4': 'Балдар',
    'cat_2_5': 'Спорт',
    'cat_2_6': 'Кышкы',
    'cat_2_7': 'Сандал/Тапочка',
    'cat_2_8': 'Жумушчу',
    'nav_store_list': 'Дүкөн\nтизмелери',

    // 3 (Аксессуарлар)
    'cat_3_1': 'Баары',
    'cat_3_2': 'Сумкалар',
    'cat_3_3': 'Кол саат',
    'cat_3_4': 'Көз айнек',
    'cat_3_5': 'Зергерчилик',
    'cat_3_6': 'Кемер',
    'cat_3_7': 'Жоолук/Шарф',
    'cat_3_8': 'Перчатка',

    // 4 (Электроника)
    'cat_4_1': 'Баары',
    'cat_4_2': 'Телефондор',
    'cat_4_3': 'Ноутбук',
    'cat_4_4': 'Планшет',
    'cat_4_5': 'Наушник',
    'cat_4_6': 'Зарядка/Кабель',
    'cat_4_7': 'Камера',
    'cat_4_8': 'Акылдуу саат',
    'cat_4_9': 'Оюн консоли',
    'cat_4_10': 'Принтер',

    // 5 (Үй буюмдар)
    'cat_5_1': 'Баары',
    'cat_5_2': 'Мебель',
    'cat_5_3': 'Жууркан/Жаздык',
    'cat_5_4': 'Идиш-аяк',
    'cat_5_5': 'Ашкана буюмдары',
    'cat_5_6': 'Үй жасалгасы',
    'cat_5_7': 'Жарык буюмдары',
    'cat_5_8': 'Килем/Чий',
    'cat_5_9': 'Штора/Пардэ',
    'cat_5_10': 'Сантехника',

    // 6 (Техника)
    'cat_6_1': 'Баары',
    'cat_6_2': 'Муздаткыч',
    'cat_6_3': 'Кир жуучу машина',
    'cat_6_4': 'Телевизор',
    'cat_6_5': 'Кондиционер',
    'cat_6_6': 'Газ плита',
    'cat_6_7': 'Микротолкундуу',
    'cat_6_8': 'Чаң соргуч',
    'cat_6_9': 'Утюг',

    // 7 (Спорт)
    'cat_7_1': 'Баары',
    'cat_7_2': 'Футбол',
    'cat_7_3': 'Баскетбол',
    'cat_7_4': 'Волейбол',
    'cat_7_5': 'Тренажер',
    'cat_7_6': 'Велосипед',
    'cat_7_7': 'Бокс',
    'cat_7_8': 'Йога/Фитнес',
    'cat_7_9': 'Сүзүү',
    'cat_7_10': 'Жүгүрүү',

    'flash_sale_title': 'Тез арада жетишип кал!',
    'flash_sale_subtitle': 'Убакыт чектелген супер баалар',
    'flash_sale_empty': 'Азырынча Flash Sale жок',
    'flash_sale_empty_sub': 'Кийинчерээк кайра кириңиз',
    'flash_time_left': 'Акция бүтүүгө калган убакыт',
    'flash_hours': 'саат',
    'flash_minutes': 'мүнөт',
    'flash_seconds': 'секунд',

// 🏆 Leaderboard
    'leaderboard_title': 'Топ алуучулар',
    'leaderboard_my_rank': 'Сиздин ордуңуз',
    'leaderboard_orders': 'буюртма',
    'leaderboard_pts': 'балл',
    'fs_search': 'Товар издөө...',
    'fs_not_found': 'Товар табылган жок',
    'fs_pick_time': '⏱️ Flash убактысын тандо',
    'fs_1h': '1 саат', 'fs_2h': '2 саат', 'fs_3h': '3 саат',
    'fs_6h': '6 саат', 'fs_12h': '12 саат', 'fs_24h': '24 саат',
    'fs_48h': '48 саат',
    'fs_pick_datetime': 'Күн жана убакыт тандоо',
    'fs_err_price': 'Flash баасын туура жазыңыз!',
    'fs_err_price_low': 'Flash баасы негизги баадан төмөн болушу керек!',
    'fs_err_time': 'Убакыт жок дегенде 5 мүнөттөн кийин болушу керек!',
    'fs_saved': '⚡ Flash Sale ийгиликтүү кошулду!',
    'fs_removed': 'Flash Sale жок кылынды 🗑️',
    'fs_orig_price': 'Негизги баа',
    'fs_active': 'Активдүү',
    'fs_flash_price': 'Flash баасы (сом)',
    'fs_example': 'Мис',
    'fs_ends_at': 'Акция бүтөт',
    'fs_time_left': 'Калган убакыт',
    'fs_timer_preview': 'Башкы экрандагы таймер',
    'fs_remove': 'Flash Sale жок кылуу',
    'fs_update': 'Flash Sale жаңылоо',
    'fs_add': 'Flash Sale кошуу',
    // 8 (Балдар)
    'cat_8_1': 'Баары',
    'cat_8_2': 'Оюнчуктар',
    'cat_8_3': 'Велосипед',
    'cat_8_4': 'Коляска',
    'cat_8_5': 'Балдар мебели',
    'cat_8_6': 'Мектеп буюмдары',
    'cat_8_7': 'Балдар китептери',
    'cat_8_8': 'Балдар тамагы',

    // 9 (Сулуулук)
    'cat_9_1': 'Баары',
    'cat_9_2': 'Жүзгө кам көрүү',
    'cat_9_3': 'Чачка кам көрүү',
    'cat_9_4': 'Парфюм',
    'cat_9_5': 'Макияж',
    'cat_9_6': 'Тырмак',
    'cat_9_7': 'Массаж буюмдары',

    // 10 (Гигиена)
    'cat_10_1': 'Баары',
    'cat_10_2': 'Шампунь/Гель',
    'cat_10_3': 'Тиш пасталары',
    'cat_10_4': 'Сабын',
    'cat_10_5': 'Дезодорант',
    'cat_10_6': 'Аялдар гигиенасы',
    'cat_10_7': 'Балдар гигиенасы',

    // 11 (Азык-түлүк)
    'cat_11_1': 'Баары',
    'cat_11_2': 'Дан азыктары',
    'cat_11_3': 'Консервалар',
    'cat_11_4': 'Майлар/Соустар',
    'cat_11_5': 'Кондитердик',
    'cat_11_6': 'Суусундуктар',
    'cat_11_7': 'Чай/Кофе',
    'cat_11_8': 'Наан/Нан',
    'cat_11_9': 'Жашылчалар',

    // 12 (Автотовар)
    'cat_12_1': 'Баары',
    'cat_12_2': 'Аксессуарлар',
    'cat_12_3': 'Автохимия',
    'cat_12_4': 'Дөңгөлөктөр',
    'cat_12_5': 'Запас бөлүктөр',
    'cat_12_6': 'Видеорегистратор',
    'cat_12_7': 'Автоаудио',
    'cat_12_8': 'Автосветтер',

    // 13 (Китеп/Канцтовар)
    'cat_13_1': 'Баары',
    'cat_13_2': 'Окуу китептери',
    'cat_13_3': 'Көркөм адабият',
    'cat_13_4': 'Балдар китептери',
    'cat_13_5': 'Дептер/Блокнот',
    'cat_13_6': 'Калем/Маркер',
    'cat_13_7': 'Рюкзак/Сумка',

    // 14 (Кездеме/Тигүү)
    'cat_14_1': 'Баары',
    'cat_14_2': 'Кездеме/Мата',
    'cat_14_3': 'Жип',
    'cat_14_4': 'Тигүү жабдуулары',
    'cat_14_5': 'Фурнитура',
    'cat_14_6': 'Вышивка',

    // 15 (Куралдар)
    'cat_15_1': 'Баары',
    'cat_15_2': 'Электр куралдары',
    'cat_15_3': 'Кол куралдары',
    'cat_15_4': 'Сантехника',
    'cat_15_5': 'Курулуш материалы',
    'cat_15_6': 'Краска/Лак',
    'cat_15_7': 'Нурдаткычтар',

    // 16 (Оюн/Эглентүү)
    'cat_16_1': 'Баары',
    'cat_16_2': 'Видеооюндар',
    'cat_16_3': 'Настолка оюндары',
    'cat_16_4': 'Пазл',
    'cat_16_5': 'Музыка аспаптары',
    'cat_16_6': 'Сүрөт тартуу',

    // 17 (Багчылык)
    'cat_17_1': 'Баары',
    'cat_17_2': 'Үй өсүмдүктөрү',
    'cat_17_3': 'Багчылык куралдары',
    'cat_17_4': 'Топурак/Жер',
    'cat_17_5': 'Уруктар',
    'cat_17_6': 'Горшок',

    // 18 (Жаныбарлар)
    'cat_18_1': 'Баары',
    'cat_18_2': 'Ит буюмдары',
    'cat_18_3': 'Мышык буюмдары',
    'cat_18_4': 'Жем/Азык',
    'cat_18_5': 'Тор/Клетка',
    'cat_18_6': 'Ветеринардык',
    'price_saved': 'сомго арзан',
    'review_count': 'адам баалады',
    'review_no_ratings': 'Азырынча баа жок',
    'your_rating': 'Сиздин бааңыз:',
    'review_login_required': 'Баа берүү үчүн кирүү керек!',
    'review_submitted': 'Баа берилди',
    'star_1': '⭐ Начар',
    'star_2': '⭐⭐ Болот',
    'star_3': '⭐⭐⭐ Жакшы',
    'star_4': '⭐⭐⭐⭐ Абдан жакшы',
    'star_5': '⭐⭐⭐⭐⭐ Мыкты!',
    'share_title': 'Бөлүшүү',
    'share_other': 'Башкалар',
    'share_copy_link': 'Шилтемени көчүрүү',
    'share_link_copied': '🔗 Шилтеме көчүрүлдү!',
    'dash_title': 'Дүкөнүм',
    'dash_manage': 'Башкаруу',
    'dash_logout_confirm': 'Дүкөндөн чыгасызбы?',
    'dash_close_account': 'Дүкөндөн баш тартуу',
    'dash_products_sub': 'Товарларды кошуу, өзгөртүү',
    'dash_stats': 'Статистика',
    'dash_stats_sub': 'Сатуу маалыматтары',
    'dash_location': 'Дүкөндүн жайгашкан жери',
    'dash_location_sub': 'Картада жериңизди белгилеңиз',
    'dash_hours': 'Иштөө убактысы',
    'dash_messages': 'Билдирүүлөр',
    'dash_new': 'жаңы',
    'dash_unread': 'окулбаган билдирүү бар',
    'dash_chat_with_customers': 'Кардарлар менен чат',
    'dash_change_phone': 'Номер өзгөртүү',
    'dash_change_phone_sub': 'Admin га өтүнүч жиберүү',
    'dash_contact_title': 'Кайрылуу үчүн',
    'dash_contact_desc':
        'Активдүү сатуучулар проблемаларын WhatsApp аркылуу жиберсин:',
    'coming_soon': 'Жакында кошулат!',

    // Жазылуу
    'sub_monthly': 'Айлык жазылуу',
    'sub_charge_info': 'Ар айдын 1-күнүндө 2 000 сом алынат',
    'sub_card_linked': 'байланган',
    'sub_new_card': 'Жаңы карта номери (алмаштыруу)',
    'sub_card_number': 'Карта номери',
    'sub_expiry': 'Мөөнөтү',
    'sub_agree_text':
        'Ар айдын 1-күнүндө картамдан 2 000 сом алынышына макулмун. Каалаган убакта токтотсо болот.',
    'sub_replace_card': '🔄  Картаны алмаштыруу',
    'sub_link_card': '✅  Картаны байлоо',
    'sub_cancel_autopay': '⛔  Авто төлөмдү токтотуу',
    'sub_remove_card': 'Картаны өчүрүү',
    'sub_card_saved': '✅ Карта байланды! Авто төлөм иштейт.',
    'sub_autopay_cancelled': '⛔ Авто төлөм токтотулду',
    'sub_card_removed': '🗑️ Карта өчүрүлдү',
    'sub_status_paid': '✅ Бул айдын төлөмү өткөрүлдү',
    'sub_status_active': '💳 Авто төлөм иштеп жатат',
    'sub_status_paused': '⏸️ Авто төлөм токтотулган',
    'sub_status_none': '💳 Жазылуу — 2 000 сом/ай',
    'sub_per_month': '2 000 сом/ай',
    'sub_charge_day': 'Айдын 1-күнүндө алынат',
    'sub_link_hint': 'Картаны байлап авто төлөм орнотуңуз',
    'loc_saved': '✅ Локация сакталды!',
    'loc_saved_label': 'Локация сакталган',
    'loc_edit': 'Локацияны өзгөртүү',
    'loc_instructions':
        '1. Google Maps же Yandex Maps ач\n2. Дүкөнүңдүн жерин тап\n3. Картага узак бас → координаттар чыгат\n4. Ошол сандарды бул жерге жаз',
    'profile_photo_updated': 'Сүрөт жаңыланды ✓',
    'profile_name_required': 'Атыңызды толтуруңуз',
    'profile_saved': 'Маалыматтар сакталды ✓',
    'profile_edit_title': 'Маалыматтарды өзгөртүү',
    'profile_label_name': 'Аты-жөнү',
    'profile_label_phone': 'Телефон',
    'profile_hint_name': 'Атыңызды жазыңыз',
    'profile_signout_confirm': 'Аккаунттан чыгасызбы?',
    'profile_signout_btn': 'Аккаунттан чыгуу',
    'profile_no_name': 'Аты жок',
    'promo_title': 'Акциялар',
    'promo_search_hint': 'Товар издөө...',
    'promo_found': 'товар табылды',
    'promo_empty': 'Азырынча акция жок',
    'promo_not_found': 'Эч нерсе табылган жок',
    'drawer_stories_title': 'Жаңылыктар',
    'drawer_story_new': 'Жаңылык',
    'drawer_story_light': 'Жеңил',
    'drawer_story_tech': 'Техника',
    'drawer_story_cloth': 'Кийим',
    'drawer_story_food': 'Тамак',
    'drawer_story_sale': 'Акция',
    'drawer_promo_title': 'Акциялар',
    'drawer_promo_subtitle': 'Арзан баадагы товарлар',
    'login_title': 'Кирүү',
    'login_heading': 'Сатуучу катары кирүү',
    'login_subheading': 'Телефон номериңиз жана паролуңуз менен кириңиз',
    'login_btn': 'Кирүү',
    'login_no_account': 'Аккаунтуңуз жокпу? Катталуу',
    'login_err_pass': 'Паролду жазыңыз',
    'login_blocked': 'Аккаунтуңуз блоктолду. Администратор менен байланышыңыз.',
    'time_now': 'Азыр',
    'time_min': 'мин',
    'time_hour': 'саат',
    'time_day': 'күн',
    'chat_image': 'Сүрөт',
    'chat_voice': 'Үн билдирүү',
    'chat_img_fail': 'Сүрөт жүктөлбөдү',
    'chat_audio_fail': 'Үн билдирүү жүктөлбөдү',
    'chat_delete_msgs_title': 'Билдирүүлөрдү өчүрүү',
    'chat_delete_msgs_body': 'билдирүү өчүрүлөт. Улантасызбы?',
    'chat_delete_msg_title': 'Билдирүүнү өчүрүү',
    'chat_delete_msg_body': 'Бул билдирүү өчүрүлөт. Улантасызбы?',
    'chat_delete_yes': 'Ооба, өчүрүү',
    'chat_buyer': 'Сатып алуучу',
    'chat_empty': 'Билдирүү жок, жазып баштаңыз',
    'chat_reply': 'Жооп',
    'chat_hint': 'Билдирүү жазыңыз...',
    'cat_1_11': 'Баш кийим',
    'story_loading': 'Жүктөлүп жатат...',
    'story_empty': 'Азырынча жаңылык жок',
    'story_add': 'Жаңылык кошуу',
    'story_image_gallery': '📷 Галереядан сүрөт',
    'story_image_camera': '📸 Камерадан тартуу',
    'story_video_gallery': '🎬 Галереядан видео',
    'story_video_camera': '🎥 Камерадан видео тартуу',
    'story_uploading': 'Жүктөлүп жатат...',
    'story_uploaded': '✅ Ийгиликтүү жүктөлдү!',
    'story_upload_error': '❌ Жүктөөдө ката чыкты',
    'story_delete_title': '🗑️ Жаңылыкты өчүрүү',
    'story_delete_body': 'Бул жаңылык толугу менен жок болот.\nУлантасызбы?',
    'story_deleted': '✅ Жаңылык өчүрүлдү',
    'story_deactivated': 'Жаңылык жашырылды',
    'story_activated': 'Жаңылык көрүнөт',
    'story_likes': 'жактыруу',
    'story_type_image': 'Сүрөт',
    'story_type_video': 'Видео',
    'story_status_active': 'Активдүү',
    'story_status_inactive': 'Өчүк',
    // ── Тандамалар экраны ──
    'fav_tab_products': 'Товарлар',
    'fav_tab_stores': 'Дүкөндөр',
    'fav_stores_empty': 'Сакталган дүкөн жок',
    'fav_stores_empty_desc': 'Жаккан дүкөнүңүздү ❤️ баскыч менен сактаңыз',
    'story_count_all': 'Баары',
    'story_refresh': 'Жаңыртуу',
    // Drawer — Flash Sale & Featured
    'drawer_flash_title': 'Тез арада жетишип кал!',
    'drawer_flash_subtitle': 'Убакыт чектелген супер баалар',
    'drawer_featured_title': 'Өзгөчө товарлар',
    'drawer_featured_subtitle': 'Сатуучулар тарабынан тандалган',

    // Admin story manager
    'admin_story_title': '📢 Жаңылыктар',
    'admin_story_subtitle':
        'Сүрөт же видео тандаңыз. Жаңылык сиз өчүрмөйүнчө туруп калат.',
    'admin_story_min_ago': 'мин мурун',
    'admin_story_hour_ago': 'саат мурун',
    'price_watch_btn': 'Баа түшсө кабарла',
    'price_watch_active': 'Күтүүдө 🔔',
    'price_watch_added': '🔔 Баа түшсө кабарлама келет!',
    'price_watch_login': 'Кирүү керек!',

    // 🎰 Рулетка — Drawer баскычы
    'drawer_roulette_title': 'Күнүмдүк Рулетка',
    'drawer_roulette_subtitle': '1 күндө 1 жолу — 1-5 упай утуп ал!',

    // 🎰 Рулетка — Экран
    'roulette_screen_title': '🎰 Күнүмдүк Рулетка',
    'roulette_spin_btn': '🎰 Айлант!',
    'roulette_wait_btn': '⏰ Эртең дагы кел',
    'roulette_used_today': 'Бүгүнкү мүмкүнчүлүк пайдаланылды',
    'roulette_login_required': 'Кирүү керек!',
    'roulette_top100': 'Топ 100',
    'roulette_empty': 'Азырынча эч ким жок',
    'roulette_my_rank': 'Сиздин ордуңуз',
    'roulette_pts': 'упай',
    'roulette_me': 'Сиз',
    'roulette_win_title': '🎉 Куттуктайбыз!',
    'roulette_win_body': 'Эртең дагы айлант!',
    'roulette_win_close': 'Жабуу',
    'roulette_period': '2 айда 1 жолу жаңыланат',
    'drawer_footer': 'Дордой базары ',
    'roulette_coming_soon':
        'Оюн азыр сынак режиминде. Жакында чыныгы белектер женүүчүлөргө берилет!',
  };

  static const _ru = {
    // 🎰 Рулетка — Drawer кнопка
    'drawer_roulette_title': 'Ежедневная Рулетка',
    'drawer_roulette_subtitle': '1 раз в день — выигрывай 1-5 очков!',
    'roulette_coming_soon':
        'Игра сейчас в тестовом режиме. Скоро победители получат настоящие призы!',
    // 🎰 Рулетка — Экран
    'roulette_screen_title': '🎰 Ежедневная Рулетка',
    'roulette_spin_btn': '🎰 Крутить!',
    'roulette_wait_btn': '⏰ Приходи завтра',
    'roulette_used_today': 'Шанс на сегодня использован',
    'roulette_login_required': 'Необходимо войти!',
    'roulette_top100': 'Топ 100',
    'roulette_empty': 'Пока никого нет',
    'roulette_my_rank': 'Твоё место',
    'roulette_pts': 'очков',
    'roulette_me': 'Ты',
    'roulette_win_title': '🎉 Поздравляем!',
    'roulette_win_body': 'Возвращайся завтра!',
    'roulette_win_close': 'Закрыть',
    'roulette_period': 'Обновляется раз в 2 месяца',

    'price_watch_btn': 'Уведоми о снижении цены',
    'price_watch_active': 'Ожидание 🔔',
    'price_watch_added': '🔔 Уведомим, когда цена снизится!',
    'price_watch_login': 'Необходимо войти!',
    'story_loading': 'Загрузка...',
    'story_empty': 'Новостей пока нет',
    'flash_sale_title': 'Успей схватить!',
    'flash_sale_subtitle': 'Супер цены — время ограничено',
    'flash_sale_empty': 'Flash Sale пока нет',
    'flash_sale_empty_sub': 'Заходите позже',
    'flash_time_left': 'До конца акции осталось',
    'flash_hours': 'часов',
    'flash_minutes': 'минут',
    'flash_seconds': 'секунд',

// 🏆 Leaderboard
    'leaderboard_title': 'Топ покупателей',

    'fs_search': 'Поиск товара...',
    'fs_not_found': 'Товар не найден',
    'fs_pick_time': '⏱️ Выберите время Flash',
    'fs_1h': '1 час', 'fs_2h': '2 часа', 'fs_3h': '3 часа',
    'fs_6h': '6 часов', 'fs_12h': '12 часов', 'fs_24h': '24 часа',
    'fs_48h': '48 часов',
    'fs_pick_datetime': 'Выбрать дату и время',
    'fs_err_price': 'Введите корректную Flash цену!',
    'fs_err_price_low': 'Flash цена должна быть ниже основной!',
    'fs_err_time': 'Время должно быть не менее чем через 5 минут!',
    // Drawer — Flash Sale & Featured
    'drawer_flash_title': 'Успей схватить!',
    'drawer_flash_subtitle': 'Супер цены на ограниченное время',
    'drawer_featured_title': 'Особые товары',
    'drawer_featured_subtitle': 'Отобранные продавцами',
    'fs_saved': '⚡ Flash Sale успешно добавлен!',
    'fs_removed': 'Flash Sale удалён 🗑️',
    'fs_orig_price': 'Основная цена',
    'fs_active': 'Активен',
    'fs_flash_price': 'Flash цена (сом)',
    'fs_example': 'Пример',
    'fs_ends_at': 'Акция заканчивается',
    // ── Избранное экран ──
    'fav_tab_products': 'Товары',
    'fav_tab_stores': 'Магазины',
    'fav_stores_empty': 'Нет сохранённых магазинов',
    'fav_stores_empty_desc': 'Сохраняйте магазины нажав ❤️',
    "drawer_footer": "Дордой",
    'fs_time_left': 'Осталось',
    'fs_timer_preview': 'Таймер на главном экране',
    'fs_remove': 'Удалить Flash Sale',
    'fs_update': 'Обновить Flash Sale',
    'fs_add': 'Добавить Flash Sale',
    'leaderboard_my_rank': 'Ваше место',
    'leaderboard_orders': 'заказов',
    'leaderboard_pts': 'баллов',
    'story_add': 'Добавить новость',
    'story_image_gallery': '📷 Фото из галереи',
    'story_image_camera': '📸 Сфотографировать',
    'story_video_gallery': '🎬 Видео из галереи',
    'story_video_camera': '🎥 Снять видео',
    'story_uploading': 'Загружается...',
    'story_uploaded': '✅ Успешно загружено!',
    'story_upload_error': '❌ Ошибка при загрузке',
    'story_delete_title': '🗑️ Удалить новость',
    'story_delete_body': 'Эта новость будет удалена навсегда.\nПродолжить?',
    'story_deleted': '✅ Новость удалена',
    'story_deactivated': 'Новость скрыта',
    'story_activated': 'Новость видна',
    'story_likes': 'лайков',
    'story_type_image': 'Фото',
    'story_type_video': 'Видео',
    'story_status_active': 'Активна',
    'story_status_inactive': 'Скрыта',
    'story_count_all': 'Все',
    'story_refresh': 'Обновить',

    // Admin story manager
    'admin_story_title': '📢 Новости',
    'admin_story_subtitle':
        'Выберите фото или видео. Новость будет показываться, пока вы её не удалите.',
    'admin_story_min_ago': 'мин назад',
    'admin_story_hour_ago': 'ч назад',

    'cat_1_11': 'Головные уборы',
    'chat_image': 'Фото',
    'chat_voice': 'Голосовое сообщение',
    'chat_img_fail': 'Не удалось загрузить фото',
    'chat_audio_fail': 'Не удалось загрузить голосовое',
    'chat_delete_msgs_title': 'Удалить сообщения',
    'chat_delete_msgs_body': 'сообщений будет удалено. Продолжить?',
    'chat_delete_msg_title': 'Удалить сообщение',
    'chat_delete_msg_body': 'Это сообщение будет удалено. Продолжить?',
    'chat_delete_yes': 'Да, удалить',
    'chat_buyer': 'Покупатель',
    'chat_empty': 'Нет сообщений, начните переписку',
    'chat_reply': 'Ответить',
    'chat_hint': 'Написать сообщение...',

    'time_now': 'Сейчас',
    'time_min': 'мин',
    'time_hour': 'ч',
    'time_day': 'д',
    'login_title': 'Войти',
    'login_heading': 'Войти как продавец',
    'login_subheading': 'Введите номер телефона и пароль',
    'login_btn': 'Войти',
    'login_no_account': 'Нет аккаунта? Зарегистрироваться',
    'login_err_pass': 'Введите пароль',
    'login_blocked': 'Ваш аккаунт заблокирован. Свяжитесь с администратором.',
    'drawer_stories_title': 'Новинки',
    'drawer_story_new': 'Новинка',
    'drawer_story_light': 'Лёгкое',
    'drawer_story_tech': 'Техника',
    'drawer_story_cloth': 'Одежда',
    'drawer_story_food': 'Еда',
    'drawer_story_sale': 'Акция',
    'drawer_promo_title': 'Акции',
    'drawer_promo_subtitle': 'Товары по сниженным ценам',
    'promo_title': 'Акции',
    'promo_search_hint': 'Поиск товара...',
    'promo_found': 'товаров найдено',
    'promo_empty': 'Пока нет акций',
    'promo_not_found': 'Ничего не найдено',
    'profile_photo_updated': 'Фото обновлено ✓',
    'profile_name_required': 'Введите своё имя',
    'profile_saved': 'Данные сохранены ✓',
    'profile_edit_title': 'Редактировать данные',
    'profile_label_name': 'Имя и фамилия',
    'profile_label_phone': 'Телефон',
    'profile_hint_name': 'Введите своё имя',
    'profile_signout_confirm': 'Выйти из аккаунта?',
    'profile_signout_btn': 'Выйти из аккаунта',
    'profile_no_name': 'Имя не указано',
    'loc_saved': '✅ Местоположение сохранено!',
    'loc_saved_label': 'Местоположение сохранено',
    'loc_edit': 'Изменить местоположение',
    'loc_instructions':
        '1. Откройте Google Maps или Yandex Maps\n2. Найдите местоположение своего магазина\n3. Долго нажмите на карту → появятся координаты\n4. Введите эти цифры здесь',
    'share_title': 'Поделиться',
    'share_other': 'Другие',
    'share_copy_link': 'Копировать ссылку',
    'share_link_copied': '🔗 Ссылка скопирована!',
    'filter_sort': 'Сортировка',
    'sort_popular': 'Популярные',
    'sort_price_asc': 'Цена: по возрастанию',
    'sort_price_desc': 'Цена: по убыванию',
    'sort_rating': 'По рейтингу',
    'sort_newest': 'Новинки',
    'filter_apply': 'Применить',
    'filter_count_suffix': 'фильтр',
    'cat_label': 'Категория',
    'cat_newest': 'Новые товары',
    'cat_popular': 'Популярное',
    'cat_select': 'Выбрать категорию',
    'pending_title': 'Ваша заявка рассматривается',
    'pending_desc':
        'Ваша заявка на регистрацию проверяется\nадминистратором. После одобрения\nвы сможете управлять своим магазином.',
    'pending_btn_home': 'Вернуться на главную',
    'rejected_title': 'Заявка отклонена',
    'rejected_desc': 'Для повторной попытки свяжитесь с администратором.',
    'settings': 'Настройки',
    'language': 'Язык',
    'notifications': 'Уведомления',
    'dark_mode': 'Тёмный режим',
    'profile': 'Профиль',
    'cache': 'Очистить кэш',
    'support': 'Поддержка',
    'terms': 'Правила',
    'home': 'Главная',
    'cart': 'Корзина',
    'favorites': 'Избранное',
    'chat': 'Чат',
    'shop': 'Магазин',
    'map_title': 'Список магазинов.',
    'map_store_count': 'магазин',
    'map_search_hint': 'Поиск магазина или контейнера...',
    'map_no_location': 'магазинов без указанного местоположения',
    'map_not_found': 'Магазин не найден',
    'map_try_search': 'Попробуйте изменить запрос',
    'price_saved': 'сом скидка',
    'review_count': 'оценили',
    'review_no_ratings': 'Оценок пока нет',
    'your_rating': 'Ваша оценка:',
    'review_login_required': 'Войдите, чтобы оставить оценку!',
    'review_submitted': 'Оценка отправлена',
    'star_1': '⭐ Плохо',
    'star_2': '⭐⭐ Нормально',
    'star_3': '⭐⭐⭐ Хорошо',
    'star_4': '⭐⭐⭐⭐ Очень хорошо',
    'star_5': '⭐⭐⭐⭐⭐ Отлично!',
    'reg_title': 'Регистрация',
    'reg_heading': 'Откройте свой магазин!',
    'reg_subheading': 'Заполните свои данные',
    'reg_label_name': 'Имя и фамилия',
    'reg_hint_name': 'Например: Айгерим Осмонова',
    'reg_label_age': 'Возраст',
    'reg_hint_age': 'Например: 28',
    'reg_label_container': 'Номер контейнера или название магазина',
    'reg_hint_container': 'Например: 4-ряд, А-12',
    'reg_label_shop': 'Название магазина (необязательно)',
    'reg_hint_shop': 'Например: Айгерим Shop',
    'reg_label_phone': 'Номер телефона',
    'reg_label_pass': 'Пароль',
    'reg_hint_pass': 'Минимум 8 символов, заглавные/строчные, цифры, знак',
    'hours_start': 'Начало',
    'hours_end': 'Конец',
    'hours_workdays': 'Рабочие дни',
    'hours_mon_fri': 'Пн-Пт',
    'hours_mon_sat': 'Пн-Сб',
    'hours_mon_sun': 'Пн-Вс',
    'hours_no_sun': 'Кроме вс',
    'hours_daily': 'Каждый день',
    'hours_saved': '✅ Часы работы сохранены',

    'reg_label_pass_confirm': 'Подтвердите пароль',
    'reg_btn_open': '🏪  Открыть магазин',
    'reg_have_account': 'Уже есть аккаунт? Войти',
    'reg_err_name': 'Введите имя и фамилию',
    'reg_err_age': 'Введите корректный возраст',
    'reg_err_container': 'Введите номер контейнера или название магазина',
    'reg_err_phone': 'Введите полный номер телефона',
    'reg_err_pass_mismatch': 'Пароли не совпадают',

    'search': 'Поиск',
    'search_hint': 'Поиск товаров...',
    'save': 'Сохранить',
    'cancel': 'Отмена',
    'delete': 'Удалить',
    'yes': 'Да',
    'no': 'Нет',
    'loading': 'Загрузка...',
    'error': 'Ошибка',
    'success': 'Успешно',
    'ok': 'Хорошо',
    'back': 'Назад',
    'close': 'Закрыть',
    'sign_out': 'Выйти',
    'product': 'Товар',
    'price': 'Цена',
    'add_to_cart': 'В корзину',
    'in_cart': 'В корзине',
    'buy_now': 'Купить сейчас',
    'description': 'Описание',
    'nav_store_list': 'Список\nмагазинов',
    'sizes': 'Размеры',
    'colors': 'Цвета',
    'characteristics': 'Характеристики',
    'similar': 'Похожие товары',
    'no_products': 'Не найдено',
    'search_empty': 'Попробуйте другой запрос',
    'popular': '🔥 Популярное',
    'newest': '🆕 Новые товары',
    'refresh': 'Обновить',
    'filter': 'Фильтр',
    'filter_reset': 'Сбросить',
    'nearby': 'Рядом со мной',
    'nearby_error':
        'Не удалось определить местоположение. Разрешите геолокацию.',
    'nearby_count': 'товаров рядом',
    'results': 'результатов',
    'camera_search': 'Поиск по фото',
    'camera_soon': 'Скоро! 🚀\nИщите товары по фотографии.',
    'seller': 'Продавец',
    'container': 'Местонахождение',
    'work_hours': 'Время работы',
    'route': 'Построить маршрут',
    'write_seller': 'Написать продавцу',
    'select_size': 'Выберите размер',
    'add_review': 'Написать отзыв',
    'dash_title': 'Мой магазин',
    'dash_manage': 'Управление',
    'dash_logout_confirm': 'Выйти из магазина?',
    'dash_close_account': 'Закрыть магазин',
    'dash_products_sub': 'Добавление и редактирование товаров',
    'dash_stats': 'Статистика',
    'dash_stats_sub': 'Данные о продажах',
    'dash_location': 'Местоположение магазина',
    'dash_location_sub': 'Отметьте своё место на карте',
    'dash_hours': 'Часы работы',
    'dash_messages': 'Сообщения',
    'dash_new': 'новых',
    'dash_unread': 'непрочитанных сообщений',
    'dash_chat_with_customers': 'Чат с покупателями',
    'dash_change_phone': 'Изменить номер',
    'dash_change_phone_sub': 'Отправить запрос администратору',
    'dash_contact_title': 'Для обращений',
    'dash_contact_desc':
        'Активные продавцы могут отправлять проблемы через WhatsApp:',
    'coming_soon': 'Скоро появится!',

    // Подписка
    'sub_monthly': 'Ежемесячная подписка',
    'sub_charge_info': '2 000 сом списывается 1-го числа каждого месяца',
    'sub_card_linked': 'привязана',
    'sub_new_card': 'Новый номер карты (замена)',
    'sub_card_number': 'Номер карты',
    'sub_expiry': 'Срок действия',
    'sub_agree_text':
        'Соглашаюсь на списание 2 000 сом с карты 1-го числа каждого месяца. Можно отменить в любое время.',
    'sub_replace_card': '🔄  Заменить карту',
    'sub_link_card': '✅  Привязать карту',
    'sub_cancel_autopay': '⛔  Отключить автоплатёж',
    'sub_remove_card': 'Удалить карту',
    'sub_card_saved': '✅ Карта привязана! Автоплатёж включён.',
    'sub_autopay_cancelled': '⛔ Автоплатёж отключён',
    'sub_card_removed': '🗑️ Карта удалена',
    'sub_status_paid': '✅ Оплата за этот месяц прошла',
    'sub_status_active': '💳 Автоплатёж активен',
    'sub_status_paused': '⏸️ Автоплатёж приостановлен',
    'sub_status_none': '💳 Подписка — 2 000 сом/мес',
    'sub_per_month': '2 000 сом/мес',
    'sub_charge_day': 'Списывается 1-го числа',
    'sub_link_hint': 'Привяжите карту для автоплатежа',

    'reviews': 'Отзывы',
    'no_reviews': 'Отзывов пока нет',
    'share': 'Поделиться',
    'cart_empty': 'Корзина пуста',
    'banner_product_label': '🛍 Товар',
    'banner_stock_label': 'На складе',
    'currency': 'с',
    'cart_empty_desc': 'Добавьте товары в корзину',
    'total': 'Итого',
    'checkout': 'Оформить заказ',
    'quantity': 'Количество',
    'favorites_empty': 'Избранное пусто',
    'favorites_empty_desc': 'Нажмите ♥ чтобы добавить товар',
    'welcome_title': 'Онлайн базар Дордоя',
    'sign_in_google': 'Войти через Google',
    'sign_in_terms': 'Войдя, вы соглашаетесь с\nусловиями использования',
    'cache_cleared': 'Кэш очищен ✅',
    'cache_error': 'Ошибка',
    'no_chats': 'Нет чатов',
    'type_message': 'Напишите сообщение...',
    'send': 'Отправить',
    'seller_title': 'Продавец',
    'login': 'Войти',
    'register': 'Зарегистрироваться',
    'shop_title': 'Управляйте своим магазином!',
    'shop_desc': 'Продавайте товары с Дордоя\nчерез DD Online по всему миру',
    'add_product': 'Добавить товар',
    'my_products': 'Мои товары',
    'no_size': 'Без размера',
    'open': 'Открыто',
    'closed': 'Закрыто',
    'no_info': 'Нет информации',
    'in_stock': 'В наличии',
    'out_of_stock': 'Нет в наличии',
    'pcs': 'шт',
    'location_denied': '📍 Разрешите геолокацию',
    'location_unknown': 'Местоположение продавца неизвестно',
    'seller_no_info': 'Нет данных о продавце!',
    'chat_login_required': 'Войдите для чата!',
    'own_product': 'Это ваш собственный товар!',
    '2gis_not_installed': '2ГИС не установлен',
    '2gis_download_hint': 'Скачайте приложение 2ГИС для построения маршрута.',
    'download': 'Скачать',
    'nav_step1': 'Нажмите кнопку ниже',
    'nav_step2': 'Откроется приложение 2ГИС',
    'nav_step3': 'Нажмите "Построить маршрут" и отправляйтесь',
    'open_2gis': 'Маршрут через 2ГИС',
    'login_error': 'Ошибка при входе',
    'seller_login': 'Войти как продавец',
    'email_not_found': 'Почтовое приложение не найдено',
    'messages': 'Сообщения',
    'selected': 'выбрано',
    'delete_chat': 'Удалить чат',
    'delete_chat_confirm': 'чат(а) будут удалены?',
    'select_all': 'Выбрать все',
    'deselect_all': 'Снять выбор',
    'new_chat': 'Новый чат',
    'cart_clear_title': 'Очистить корзину',
    'cart_clear_confirm': 'Удалить все товары?',
    'back_to_products': 'Вернуться к товарам',
    'size_label': 'Размер',
    'items_count': 'Количество товаров:',
    'total_price': 'Итого:',
    'order_placed': 'Заказ оформлен!',
    'order_placed_desc': 'Ваш заказ принят! Свяжитесь с продавцом через чат.',
    'great': 'Отлично!',
    'prod_all': 'Все',
    'prod_empty': 'Нет товаров',
    'prod_empty_hint': 'Нажмите кнопку + внизу, чтобы добавить товар',
    'prod_empty_cat': 'В этой категории нет товаров',
    'prod_empty_cat_hint': 'Выберите другую категорию',
    'prod_delete_title': 'Удалить товар',
    'prod_delete_confirm': 'товар будет удалён?',
    'prod_delete_yes': 'Да, удалить',
    'prod_deleted': 'Товар удалён',
    'prod_delete_error': 'Ошибка при удалении',
    'prod_load_error': 'Ошибка загрузки товаров',
    'prod_img_upload_fail': 'Не удалось загрузить фото',
    'prod_check_internet': 'Проверьте подключение к интернету',
    'discount_title': '🏷️ Установить скидку',
    'discount_original_price': 'Исходная цена',
    'discount_percent_label': 'Процент скидки (0–100)',
    'discount_label': 'скидка',
    'discount_saved': 'сом скидка',
    'discount_add_btn': 'Добавить в акцию',
    'discount_remove_btn': 'Убрать акцию',
    'discount_removed': 'Акция удалена',
    'discount_saved_msg': '✅ Акция сохранена! Товар добавлен в раздел акций.',
    'prod_dialog_add': 'Добавить товар',
    'prod_dialog_edit': 'Редактировать товар',
    'prod_field_image': '🖼️ Фото товара *',
    'prod_field_name': '📝 Название товара *',
    'prod_hint_name': 'Например: Чёрное шёлковое платье',
    'prod_field_price': '💰 Цена (сом) *',
    'prod_hint_price': 'Например: 1200',
    'prod_field_main_cat': '🗂️ Основная категория *',
    'prod_field_sub_cat': '📁 Подкатегория',
    'prod_sub_cat_general': 'Общая',
    'prod_field_colors': '🎨 Цвета (по желанию)',
    'prod_size_men': '👔 Размер мужской одежды',
    'prod_size_women': '👗 Размер женской одежды',
    'prod_size_kids': '👶 Возраст / размер детей',
    'prod_size_school': '📏 Размер школьной формы (по росту)',
    'prod_size_shoes': '👟 Размер обуви (дети 16-35, взрослые 36-47)',
    'prod_size_fabric': '🧵 Выберите метраж',
    'prod_size_default': '📏 Выберите размеры',
    'prod_field_brand': '🏷️ Бренд',
    'prod_hint_brand_tech': 'Например: Samsung, Apple, LG',
    'prod_field_model': '📋 Модель',
    'prod_hint_model': 'Например: Galaxy S24, iPhone 15',
    'prod_field_spec': '🔌 Технические характеристики',
    'prod_hint_spec': 'Например: 256GB, 4K, 2000Вт',
    'prod_hint_brand_beauty': 'Например: Nivea, L\'Oreal',
    'prod_field_volume': '🧴 Объём / Вес',
    'prod_hint_volume': 'Например: 200мл, 50г',
    'prod_hint_brand_auto': 'Например: Bosch, Michelin',
    'prod_field_car_compat': '🚗 Подходит для автомобилей',
    'prod_hint_car_compat': 'Например: Toyota Camry, Kia Cerato',
    'prod_field_stock': '📦 Количество на складе',
    'prod_hint_stock': 'Например: 50',
    'prod_field_desc': '📄 Описание',
    'prod_hint_desc': 'Краткое описание товара...',
    'prod_required_note': '* Поля, отмеченные звёздочкой, обязательны.',
    'prod_err_name': 'Введите название товара!',
    'prod_err_price': 'Введите корректную цену!',
    'prod_err_image': 'Выберите фото!',
    'prod_uploading': 'Загрузка фото...',
    'prod_uploaded': '✅ Фото загружено',
    'prod_saving': 'Сохранение товара...',
    'prod_added': '✅ Товар успешно добавлен!',
    'prod_updated': '✅ Товар обновлён!',
    'prod_save_error': 'Произошла ошибка',
    'prod_btn_save': 'Сохранить товар',
    'prod_btn_update': 'Сохранить изменения',
    'prod_img_tap': 'Нажмите, чтобы добавить фото',
    'prod_img_camera': 'Сфотографировать',
    'prod_img_gallery': 'Выбрать из галереи',
    'prod_img_pick_error': 'Ошибка при выборе фото',
    'terms_title': 'Правила и политика конфиденциальности',
    'terms_s1_title': '1. Общие условия',
    'terms_s1_body':
        'DD Online — онлайн-платформа, объединяющая продавцов и покупателей рынка Дордой. Устанавливая и используя приложение, вы подтверждаете, что принимаете правила и политику конфиденциальности, указанные на этой странице.',
    'terms_s2_title': '2. Роль платформы',
    'terms_s2_body':
        'DD Online не продаёт товары напрямую. Платформа служит для связи продавцов и покупателей, поиска товаров и отображения маршрута до магазина. Ответственность за цену, качество, наличие и условия продажи товара несёт продавец, разместивший объявление.',
    'terms_s3_title': '3. Обязанности пользователя',
    'terms_s3_body':
        'Пользователь обязуется указывать достоверные данные при регистрации, вести себя уважительно по отношению к другим пользователям и продавцам, не размещать незаконный, мошеннический или вредоносный контент. При нарушении этих правил профиль может быть временно или навсегда заблокирован.',
    'terms_s4_title': '4. Правила для продавцов',
    'terms_s4_body':
        'Фотографии, цена и описание товара, размещённого продавцом, должны соответствовать действительности. Запрещено размещать запрещённые, контрафактные или незаконные товары. Администрация оставляет за собой право удалять сомнительные объявления или блокировать аккаунт продавца без предупреждения.',
    'terms_s5_title': '5. Политика конфиденциальности',
    'terms_s5_body':
        'Мы собираем такие данные, как ваше имя, номер телефона, местоположение (геолокация) и история переписки внутри приложения. Эти данные используются для: регистрации и аутентификации, связи продавца с покупателем, построения маршрута до магазина, улучшения качества работы приложения и отправки уведомлений.',
    'terms_s6_title': '6. Хранение и защита данных',
    'terms_s6_body':
        'Данные пользователей хранятся на зашифрованных серверах и не продаются третьим лицам. Данные могут использоваться исключительно для обеспечения связи между продавцом и покупателем, а также в целях статистики и безопасности. Пользователь может в любое время запросить удаление своего профиля и персональных данных.',
    'terms_s7_title': '7. Геолокация и карта',
    'terms_s7_body':
        'Приложение запрашивает доступ к вашему местоположению для функции "Построить маршрут". Эти данные используются только на вашем устройстве и передаются в стороннее приложение (например, 2ГИС) исключительно для построения маршрута.',
    'terms_s8_title': '8. Изменение правил',
    'terms_s8_body':
        'Администрация периодически обновляет данные правила и политику конфиденциальности. О важных изменениях пользователи будут уведомлены через приложение.',
    'terms_s9_title': '9. Контакты',
    'terms_s9_body':
        'По вопросам, жалобам или предложениям вы можете обратиться к нам по следующим контактам:',
    'terms_contact_addr': 'Рынок Дордой, Бишкек, Кыргызстан',
    'terms_disclaimer':
        'Этот документ составлен в информационных целях и не является юридической консультацией.',
    // Негизги категориялар
    'cat_1': 'Одежда',
    'cat_2': 'Обувь',
    'cat_3': 'Аксессуары',
    'cat_4': 'Электроника',
    'cat_5': 'Товары для дома',
    'cat_6': 'Бытовая техника',
    'cat_7': 'Спорт',
    'cat_8': 'Детские товары',
    'cat_9': 'Красота',
    'cat_10': 'Гигиена',
    'cat_11': 'Продукты питания',
    'cat_12': 'Автотовары',
    'cat_13': 'Книги/Канцтовары',
    'cat_14': 'Ткани/Шитьё',
    'cat_15': 'Инструменты',
    'cat_16': 'Игры/Развлечения',
    'cat_17': 'Садоводство',
    'cat_18': 'Товары для животных',

    // 1 (Одежда)
    'cat_1_1': 'Все',
    'cat_1_2': 'Мужская',
    'cat_1_3': 'Женская',
    'cat_1_4': 'Детская',
    'cat_1_5': 'Школьная форма',
    'cat_1_6': 'Зимняя одежда',
    'cat_1_7': 'Летняя одежда',
    'cat_1_8': 'Спортивная',
    'cat_1_9': 'Рабочая одежда',
    'cat_1_10': 'Национальная',

    // 2 (Обувь)
    'cat_2_1': 'Все',
    'cat_2_2': 'Мужская',
    'cat_2_3': 'Женская',
    'cat_2_4': 'Детская',
    'cat_2_5': 'Спортивная',
    'cat_2_6': 'Зимняя',
    'cat_2_7': 'Сандали/Тапки',
    'cat_2_8': 'Рабочая',

    // 3 (Аксессуары)
    'cat_3_1': 'Все',
    'cat_3_2': 'Сумки',
    'cat_3_3': 'Часы',
    'cat_3_4': 'Очки',
    'cat_3_5': 'Украшения',
    'cat_3_6': 'Ремень',
    'cat_3_7': 'Платок/Шарф',
    'cat_3_8': 'Перчатки',

    // 4 (Электроника)
    'cat_4_1': 'Все',
    'cat_4_2': 'Телефоны',
    'cat_4_3': 'Ноутбуки',
    'cat_4_4': 'Планшеты',
    'cat_4_5': 'Наушники',
    'cat_4_6': 'Зарядка/Кабель',
    'cat_4_7': 'Камера',
    'cat_4_8': 'Умные часы',
    'cat_4_9': 'Игровая консоль',
    'cat_4_10': 'Принтер',

    // 5 (Товары для дома)
    'cat_5_1': 'Все',
    'cat_5_2': 'Мебель',
    'cat_5_3': 'Одеяло/Подушка',
    'cat_5_4': 'Посуда',
    'cat_5_5': 'Кухонные товары',
    'cat_5_6': 'Декор',
    'cat_5_7': 'Освещение',
    'cat_5_8': 'Ковёр/Циновка',
    'cat_5_9': 'Шторы',
    'cat_5_10': 'Сантехника',

    // 6 (Бытовая техника)
    'cat_6_1': 'Все',
    'cat_6_2': 'Холодильник',
    'cat_6_3': 'Стиральная машина',
    'cat_6_4': 'Телевизор',
    'cat_6_5': 'Кондиционер',
    'cat_6_6': 'Газовая плита',
    'cat_6_7': 'Микроволновка',
    'cat_6_8': 'Пылесос',
    'cat_6_9': 'Утюг',

    // 7 (Спорт)
    'cat_7_1': 'Все',
    'cat_7_2': 'Футбол',
    'cat_7_3': 'Баскетбол',
    'cat_7_4': 'Волейбол',
    'cat_7_5': 'Тренажёр',
    'cat_7_6': 'Велосипед',
    'cat_7_7': 'Бокс',
    'cat_7_8': 'Йога/Фитнес',
    'cat_7_9': 'Плавание',
    'cat_7_10': 'Бег',

    // 8 (Детские товары)
    'cat_8_1': 'Все',
    'cat_8_2': 'Игрушки',
    'cat_8_3': 'Велосипед',
    'cat_8_4': 'Коляска',
    'cat_8_5': 'Детская мебель',
    'cat_8_6': 'Школьные товары',
    'cat_8_7': 'Детские книги',
    'cat_8_8': 'Детское питание',

    // 9 (Красота)
    'cat_9_1': 'Все',
    'cat_9_2': 'Уход за лицом',
    'cat_9_3': 'Уход за волосами',
    'cat_9_4': 'Парфюм',
    'cat_9_5': 'Макияж',
    'cat_9_6': 'Ногти',
    'cat_9_7': 'Массаж',

    // 10 (Гигиена)
    'cat_10_1': 'Все',
    'cat_10_2': 'Шампунь/Гель',
    'cat_10_3': 'Зубные пасты',
    'cat_10_4': 'Мыло',
    'cat_10_5': 'Дезодорант',
    'cat_10_6': 'Женская гигиена',
    'cat_10_7': 'Детская гигиена',

    // 11 (Продукты питания)
    'cat_11_1': 'Все',
    'cat_11_2': 'Крупы',
    'cat_11_3': 'Консервы',
    'cat_11_4': 'Масла/Соусы',
    'cat_11_5': 'Кондитерские',
    'cat_11_6': 'Напитки',
    'cat_11_7': 'Чай/Кофе',
    'cat_11_8': 'Хлеб/Выпечка',
    'cat_11_9': 'Овощи/Фрукты',

    // 12 (Автотовары)
    'cat_12_1': 'Все',
    'cat_12_2': 'Аксессуары',
    'cat_12_3': 'Автохимия',
    'cat_12_4': 'Шины/Диски',
    'cat_12_5': 'Запчасти',
    'cat_12_6': 'Видеорегистратор',
    'cat_12_7': 'Автоаудио',
    'cat_12_8': 'Автосвет',

    // 13 (Книги/Канцтовары)
    'cat_13_1': 'Все',
    'cat_13_2': 'Учебники',
    'cat_13_3': 'Художественная',
    'cat_13_4': 'Детские книги',
    'cat_13_5': 'Тетрадь/Блокнот',
    'cat_13_6': 'Ручки/Маркеры',
    'cat_13_7': 'Рюкзак/Сумка',

    // 14 (Ткани/Шитьё)
    'cat_14_1': 'Все',
    'cat_14_2': 'Ткань/Материал',
    'cat_14_3': 'Нитки',
    'cat_14_4': 'Швейное оборудование',
    'cat_14_5': 'Фурнитура',
    'cat_14_6': 'Вышивка',

    // 15 (Инструменты)
    'cat_15_1': 'Все',
    'cat_15_2': 'Электроинструменты',
    'cat_15_3': 'Ручные инструменты',
    'cat_15_4': 'Сантехника',
    'cat_15_5': 'Стройматериалы',
    'cat_15_6': 'Краска/Лак',
    'cat_15_7': 'Фонари/Освещение',

    // 16 (Игры/Развлечения)
    'cat_16_1': 'Все',
    'cat_16_2': 'Видеоигры',
    'cat_16_3': 'Настольные игры',
    'cat_16_4': 'Пазл',
    'cat_16_5': 'Музыкальные инструменты',
    'cat_16_6': 'Рисование',

    // 17 (Садоводство)
    'cat_17_1': 'Все',
    'cat_17_2': 'Комнатные растения',
    'cat_17_3': 'Садовые инструменты',
    'cat_17_4': 'Грунт/Земля',
    'cat_17_5': 'Семена',
    'cat_17_6': 'Горшки/Кашпо',

    // 18 (Товары для животных)
    'cat_18_1': 'Все',
    'cat_18_2': 'Для собак',
    'cat_18_3': 'Для кошек',
    'cat_18_4': 'Корм/Питание',
    'cat_18_5': 'Клетки/Вольеры',
    'cat_18_6': 'Ветеринария',
  };

  String get(String key) {
    final map = locale.languageCode == 'ru' ? _ru : _ky;
    return map[key] ?? key;
  }
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['ky', 'ru'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async =>
      AppLocalizations(locale);

  @override
  bool shouldReload(_) => false;
}
